name: Update thumbnails.json
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          python ./.github/script/generate_json.py > thumbnails.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[ACTIONS] Update JSON"
          git push
